import makeColorScheme from './../../makeColorScheme';

import avocadoScheme from './avocado';
import blueberryScheme from './blueberry';
import caraCaraMorelScheme from './caraCaraMorel';
import caraCaraScheme from './caraCara';
import fujiAppleScheme from './fujiApple';
import mangoCaraCaraScheme from './mangoCaraCara';
import mangoFujiAppleScheme from './mangoFujiApple';
import mangoMorelScheme from './mangoMorel';
import mangoScheme from './mango';
import mintChocolateSesameScheme from './mintChocolateSesame';
import mintChocolateScheme from './mintChocolate';
import morelScheme from './morel';
import morningGloryBlueberryScheme from './morningGloryBlueberry';
import morningGloryScheme from './morningGlory';
import pistachioScheme from './pistachio';
import plumScheme from './plum';
import sesameScheme from './sesame';

export const avocado = makeColorScheme(avocadoScheme);
export const blueberry = makeColorScheme(blueberryScheme);
export const caraCaraMorel = makeColorScheme(caraCaraMorelScheme);
export const caraCara = makeColorScheme(caraCaraScheme);
export const fujiApple = makeColorScheme(fujiAppleScheme);
export const mangoCaraCara = makeColorScheme(mangoCaraCaraScheme);
export const mangoFujiApple = makeColorScheme(mangoFujiAppleScheme);
export const mangoMorel = makeColorScheme(mangoMorelScheme);
export const mango = makeColorScheme(mangoScheme);
export const mintChocolateSesame = makeColorScheme(mintChocolateSesameScheme);
export const mintChocolate = makeColorScheme(mintChocolateScheme);
export const morel = makeColorScheme(morelScheme);
export const morningGloryBlueberry = makeColorScheme(morningGloryBlueberryScheme);
export const morningGlory = makeColorScheme(morningGloryScheme);
export const pistachio = makeColorScheme(pistachioScheme);
export const plum = makeColorScheme(plumScheme);
export const sesame = makeColorScheme(sesameScheme);
